'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.261.
'
Namespace wsAuto_DB
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WebServiceSoap", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Object()))>  _
    Partial Public Class WebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private auto_verhuurOperationCompleted As System.Threading.SendOrPostCallback
        
        Private auto_addOperationCompleted As System.Threading.SendOrPostCallback
        
        Private auto_updateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private auto_removeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private auto_getDataSetAutoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private klant_LoginOperationCompleted As System.Threading.SendOrPostCallback
        
        Private klant_insertOperationCompleted As System.Threading.SendOrPostCallback
        
        Private klant_updateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private klant_removeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private klant_getDataSetKlantOperationCompleted As System.Threading.SendOrPostCallback
        
        Private verhuur_addOperationCompleted As System.Threading.SendOrPostCallback
        
        Private verhuur_updateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private verhuur_removeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private verhuur_getDataSetVerhuurOperationCompleted As System.Threading.SendOrPostCallback
        
        Private connectionTestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private admin_LoginOperationCompleted As System.Threading.SendOrPostCallback
        
        Private admin_GetDataSetAdminOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Groepswerk.My.MySettings.Default.Groepswerk_wsAuto_DB_WebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event auto_verhuurCompleted As auto_verhuurCompletedEventHandler
        
        '''<remarks/>
        Public Event auto_addCompleted As auto_addCompletedEventHandler
        
        '''<remarks/>
        Public Event auto_updateCompleted As auto_updateCompletedEventHandler
        
        '''<remarks/>
        Public Event auto_removeCompleted As auto_removeCompletedEventHandler
        
        '''<remarks/>
        Public Event auto_getDataSetAutoCompleted As auto_getDataSetAutoCompletedEventHandler
        
        '''<remarks/>
        Public Event klant_LoginCompleted As klant_LoginCompletedEventHandler
        
        '''<remarks/>
        Public Event klant_insertCompleted As klant_insertCompletedEventHandler
        
        '''<remarks/>
        Public Event klant_updateCompleted As klant_updateCompletedEventHandler
        
        '''<remarks/>
        Public Event klant_removeCompleted As klant_removeCompletedEventHandler
        
        '''<remarks/>
        Public Event klant_getDataSetKlantCompleted As klant_getDataSetKlantCompletedEventHandler
        
        '''<remarks/>
        Public Event verhuur_addCompleted As verhuur_addCompletedEventHandler
        
        '''<remarks/>
        Public Event verhuur_updateCompleted As verhuur_updateCompletedEventHandler
        
        '''<remarks/>
        Public Event verhuur_removeCompleted As verhuur_removeCompletedEventHandler
        
        '''<remarks/>
        Public Event verhuur_getDataSetVerhuurCompleted As verhuur_getDataSetVerhuurCompletedEventHandler
        
        '''<remarks/>
        Public Event connectionTestCompleted As connectionTestCompletedEventHandler
        
        '''<remarks/>
        Public Event admin_LoginCompleted As admin_LoginCompletedEventHandler
        
        '''<remarks/>
        Public Event admin_GetDataSetAdminCompleted As admin_GetDataSetAdminCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/auto_verhuur", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function auto_verhuur(ByVal gegevensArray() As Object) As String
            Dim results() As Object = Me.Invoke("auto_verhuur", New Object() {gegevensArray})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub auto_verhuurAsync(ByVal gegevensArray() As Object)
            Me.auto_verhuurAsync(gegevensArray, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub auto_verhuurAsync(ByVal gegevensArray() As Object, ByVal userState As Object)
            If (Me.auto_verhuurOperationCompleted Is Nothing) Then
                Me.auto_verhuurOperationCompleted = AddressOf Me.Onauto_verhuurOperationCompleted
            End If
            Me.InvokeAsync("auto_verhuur", New Object() {gegevensArray}, Me.auto_verhuurOperationCompleted, userState)
        End Sub
        
        Private Sub Onauto_verhuurOperationCompleted(ByVal arg As Object)
            If (Not (Me.auto_verhuurCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent auto_verhuurCompleted(Me, New auto_verhuurCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/auto_add", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function auto_add(ByVal gegevensArray() As Object) As String
            Dim results() As Object = Me.Invoke("auto_add", New Object() {gegevensArray})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub auto_addAsync(ByVal gegevensArray() As Object)
            Me.auto_addAsync(gegevensArray, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub auto_addAsync(ByVal gegevensArray() As Object, ByVal userState As Object)
            If (Me.auto_addOperationCompleted Is Nothing) Then
                Me.auto_addOperationCompleted = AddressOf Me.Onauto_addOperationCompleted
            End If
            Me.InvokeAsync("auto_add", New Object() {gegevensArray}, Me.auto_addOperationCompleted, userState)
        End Sub
        
        Private Sub Onauto_addOperationCompleted(ByVal arg As Object)
            If (Not (Me.auto_addCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent auto_addCompleted(Me, New auto_addCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/auto_update", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function auto_update(ByVal gegevensArray() As Object) As String
            Dim results() As Object = Me.Invoke("auto_update", New Object() {gegevensArray})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub auto_updateAsync(ByVal gegevensArray() As Object)
            Me.auto_updateAsync(gegevensArray, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub auto_updateAsync(ByVal gegevensArray() As Object, ByVal userState As Object)
            If (Me.auto_updateOperationCompleted Is Nothing) Then
                Me.auto_updateOperationCompleted = AddressOf Me.Onauto_updateOperationCompleted
            End If
            Me.InvokeAsync("auto_update", New Object() {gegevensArray}, Me.auto_updateOperationCompleted, userState)
        End Sub
        
        Private Sub Onauto_updateOperationCompleted(ByVal arg As Object)
            If (Not (Me.auto_updateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent auto_updateCompleted(Me, New auto_updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/auto_remove", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function auto_remove(ByVal autoID As Integer) As String
            Dim results() As Object = Me.Invoke("auto_remove", New Object() {autoID})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub auto_removeAsync(ByVal autoID As Integer)
            Me.auto_removeAsync(autoID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub auto_removeAsync(ByVal autoID As Integer, ByVal userState As Object)
            If (Me.auto_removeOperationCompleted Is Nothing) Then
                Me.auto_removeOperationCompleted = AddressOf Me.Onauto_removeOperationCompleted
            End If
            Me.InvokeAsync("auto_remove", New Object() {autoID}, Me.auto_removeOperationCompleted, userState)
        End Sub
        
        Private Sub Onauto_removeOperationCompleted(ByVal arg As Object)
            If (Not (Me.auto_removeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent auto_removeCompleted(Me, New auto_removeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/auto_getDataSetAuto", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function auto_getDataSetAuto() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("auto_getDataSetAuto", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub auto_getDataSetAutoAsync()
            Me.auto_getDataSetAutoAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub auto_getDataSetAutoAsync(ByVal userState As Object)
            If (Me.auto_getDataSetAutoOperationCompleted Is Nothing) Then
                Me.auto_getDataSetAutoOperationCompleted = AddressOf Me.Onauto_getDataSetAutoOperationCompleted
            End If
            Me.InvokeAsync("auto_getDataSetAuto", New Object(-1) {}, Me.auto_getDataSetAutoOperationCompleted, userState)
        End Sub
        
        Private Sub Onauto_getDataSetAutoOperationCompleted(ByVal arg As Object)
            If (Not (Me.auto_getDataSetAutoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent auto_getDataSetAutoCompleted(Me, New auto_getDataSetAutoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/klant_Login", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function klant_Login(ByVal Emailadres As String, ByVal Wachtwoord As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("klant_Login", New Object() {Emailadres, Wachtwoord})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub klant_LoginAsync(ByVal Emailadres As String, ByVal Wachtwoord As String)
            Me.klant_LoginAsync(Emailadres, Wachtwoord, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub klant_LoginAsync(ByVal Emailadres As String, ByVal Wachtwoord As String, ByVal userState As Object)
            If (Me.klant_LoginOperationCompleted Is Nothing) Then
                Me.klant_LoginOperationCompleted = AddressOf Me.Onklant_LoginOperationCompleted
            End If
            Me.InvokeAsync("klant_Login", New Object() {Emailadres, Wachtwoord}, Me.klant_LoginOperationCompleted, userState)
        End Sub
        
        Private Sub Onklant_LoginOperationCompleted(ByVal arg As Object)
            If (Not (Me.klant_LoginCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent klant_LoginCompleted(Me, New klant_LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/klant_insert", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function klant_insert(ByVal gegevensArray() As Object) As String
            Dim results() As Object = Me.Invoke("klant_insert", New Object() {gegevensArray})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub klant_insertAsync(ByVal gegevensArray() As Object)
            Me.klant_insertAsync(gegevensArray, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub klant_insertAsync(ByVal gegevensArray() As Object, ByVal userState As Object)
            If (Me.klant_insertOperationCompleted Is Nothing) Then
                Me.klant_insertOperationCompleted = AddressOf Me.Onklant_insertOperationCompleted
            End If
            Me.InvokeAsync("klant_insert", New Object() {gegevensArray}, Me.klant_insertOperationCompleted, userState)
        End Sub
        
        Private Sub Onklant_insertOperationCompleted(ByVal arg As Object)
            If (Not (Me.klant_insertCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent klant_insertCompleted(Me, New klant_insertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/klant_update", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function klant_update(ByVal gegevensArray() As Object) As String
            Dim results() As Object = Me.Invoke("klant_update", New Object() {gegevensArray})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub klant_updateAsync(ByVal gegevensArray() As Object)
            Me.klant_updateAsync(gegevensArray, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub klant_updateAsync(ByVal gegevensArray() As Object, ByVal userState As Object)
            If (Me.klant_updateOperationCompleted Is Nothing) Then
                Me.klant_updateOperationCompleted = AddressOf Me.Onklant_updateOperationCompleted
            End If
            Me.InvokeAsync("klant_update", New Object() {gegevensArray}, Me.klant_updateOperationCompleted, userState)
        End Sub
        
        Private Sub Onklant_updateOperationCompleted(ByVal arg As Object)
            If (Not (Me.klant_updateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent klant_updateCompleted(Me, New klant_updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/klant_remove", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function klant_remove(ByVal klantID As Integer) As String
            Dim results() As Object = Me.Invoke("klant_remove", New Object() {klantID})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub klant_removeAsync(ByVal klantID As Integer)
            Me.klant_removeAsync(klantID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub klant_removeAsync(ByVal klantID As Integer, ByVal userState As Object)
            If (Me.klant_removeOperationCompleted Is Nothing) Then
                Me.klant_removeOperationCompleted = AddressOf Me.Onklant_removeOperationCompleted
            End If
            Me.InvokeAsync("klant_remove", New Object() {klantID}, Me.klant_removeOperationCompleted, userState)
        End Sub
        
        Private Sub Onklant_removeOperationCompleted(ByVal arg As Object)
            If (Not (Me.klant_removeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent klant_removeCompleted(Me, New klant_removeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/klant_getDataSetKlant", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function klant_getDataSetKlant() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("klant_getDataSetKlant", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub klant_getDataSetKlantAsync()
            Me.klant_getDataSetKlantAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub klant_getDataSetKlantAsync(ByVal userState As Object)
            If (Me.klant_getDataSetKlantOperationCompleted Is Nothing) Then
                Me.klant_getDataSetKlantOperationCompleted = AddressOf Me.Onklant_getDataSetKlantOperationCompleted
            End If
            Me.InvokeAsync("klant_getDataSetKlant", New Object(-1) {}, Me.klant_getDataSetKlantOperationCompleted, userState)
        End Sub
        
        Private Sub Onklant_getDataSetKlantOperationCompleted(ByVal arg As Object)
            If (Not (Me.klant_getDataSetKlantCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent klant_getDataSetKlantCompleted(Me, New klant_getDataSetKlantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verhuur_add", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function verhuur_add(ByVal gegevensArray() As Object) As Boolean
            Dim results() As Object = Me.Invoke("verhuur_add", New Object() {gegevensArray})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub verhuur_addAsync(ByVal gegevensArray() As Object)
            Me.verhuur_addAsync(gegevensArray, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub verhuur_addAsync(ByVal gegevensArray() As Object, ByVal userState As Object)
            If (Me.verhuur_addOperationCompleted Is Nothing) Then
                Me.verhuur_addOperationCompleted = AddressOf Me.Onverhuur_addOperationCompleted
            End If
            Me.InvokeAsync("verhuur_add", New Object() {gegevensArray}, Me.verhuur_addOperationCompleted, userState)
        End Sub
        
        Private Sub Onverhuur_addOperationCompleted(ByVal arg As Object)
            If (Not (Me.verhuur_addCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent verhuur_addCompleted(Me, New verhuur_addCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verhuur_update", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function verhuur_update(ByVal gegevensArray() As Object) As String
            Dim results() As Object = Me.Invoke("verhuur_update", New Object() {gegevensArray})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub verhuur_updateAsync(ByVal gegevensArray() As Object)
            Me.verhuur_updateAsync(gegevensArray, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub verhuur_updateAsync(ByVal gegevensArray() As Object, ByVal userState As Object)
            If (Me.verhuur_updateOperationCompleted Is Nothing) Then
                Me.verhuur_updateOperationCompleted = AddressOf Me.Onverhuur_updateOperationCompleted
            End If
            Me.InvokeAsync("verhuur_update", New Object() {gegevensArray}, Me.verhuur_updateOperationCompleted, userState)
        End Sub
        
        Private Sub Onverhuur_updateOperationCompleted(ByVal arg As Object)
            If (Not (Me.verhuur_updateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent verhuur_updateCompleted(Me, New verhuur_updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verhuur_remove", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function verhuur_remove(ByVal verhuurID As Integer) As String
            Dim results() As Object = Me.Invoke("verhuur_remove", New Object() {verhuurID})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub verhuur_removeAsync(ByVal verhuurID As Integer)
            Me.verhuur_removeAsync(verhuurID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub verhuur_removeAsync(ByVal verhuurID As Integer, ByVal userState As Object)
            If (Me.verhuur_removeOperationCompleted Is Nothing) Then
                Me.verhuur_removeOperationCompleted = AddressOf Me.Onverhuur_removeOperationCompleted
            End If
            Me.InvokeAsync("verhuur_remove", New Object() {verhuurID}, Me.verhuur_removeOperationCompleted, userState)
        End Sub
        
        Private Sub Onverhuur_removeOperationCompleted(ByVal arg As Object)
            If (Not (Me.verhuur_removeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent verhuur_removeCompleted(Me, New verhuur_removeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verhuur_getDataSetVerhuur", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function verhuur_getDataSetVerhuur() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("verhuur_getDataSetVerhuur", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub verhuur_getDataSetVerhuurAsync()
            Me.verhuur_getDataSetVerhuurAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub verhuur_getDataSetVerhuurAsync(ByVal userState As Object)
            If (Me.verhuur_getDataSetVerhuurOperationCompleted Is Nothing) Then
                Me.verhuur_getDataSetVerhuurOperationCompleted = AddressOf Me.Onverhuur_getDataSetVerhuurOperationCompleted
            End If
            Me.InvokeAsync("verhuur_getDataSetVerhuur", New Object(-1) {}, Me.verhuur_getDataSetVerhuurOperationCompleted, userState)
        End Sub
        
        Private Sub Onverhuur_getDataSetVerhuurOperationCompleted(ByVal arg As Object)
            If (Not (Me.verhuur_getDataSetVerhuurCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent verhuur_getDataSetVerhuurCompleted(Me, New verhuur_getDataSetVerhuurCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/connectionTest", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function connectionTest() As Boolean
            Dim results() As Object = Me.Invoke("connectionTest", New Object(-1) {})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub connectionTestAsync()
            Me.connectionTestAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub connectionTestAsync(ByVal userState As Object)
            If (Me.connectionTestOperationCompleted Is Nothing) Then
                Me.connectionTestOperationCompleted = AddressOf Me.OnconnectionTestOperationCompleted
            End If
            Me.InvokeAsync("connectionTest", New Object(-1) {}, Me.connectionTestOperationCompleted, userState)
        End Sub
        
        Private Sub OnconnectionTestOperationCompleted(ByVal arg As Object)
            If (Not (Me.connectionTestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent connectionTestCompleted(Me, New connectionTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/admin_Login", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function admin_Login(ByVal Emailadres As String, ByVal Wachtwoord As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("admin_Login", New Object() {Emailadres, Wachtwoord})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub admin_LoginAsync(ByVal Emailadres As String, ByVal Wachtwoord As String)
            Me.admin_LoginAsync(Emailadres, Wachtwoord, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub admin_LoginAsync(ByVal Emailadres As String, ByVal Wachtwoord As String, ByVal userState As Object)
            If (Me.admin_LoginOperationCompleted Is Nothing) Then
                Me.admin_LoginOperationCompleted = AddressOf Me.Onadmin_LoginOperationCompleted
            End If
            Me.InvokeAsync("admin_Login", New Object() {Emailadres, Wachtwoord}, Me.admin_LoginOperationCompleted, userState)
        End Sub
        
        Private Sub Onadmin_LoginOperationCompleted(ByVal arg As Object)
            If (Not (Me.admin_LoginCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent admin_LoginCompleted(Me, New admin_LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/admin_GetDataSetAdmin", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function admin_GetDataSetAdmin() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("admin_GetDataSetAdmin", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub admin_GetDataSetAdminAsync()
            Me.admin_GetDataSetAdminAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub admin_GetDataSetAdminAsync(ByVal userState As Object)
            If (Me.admin_GetDataSetAdminOperationCompleted Is Nothing) Then
                Me.admin_GetDataSetAdminOperationCompleted = AddressOf Me.Onadmin_GetDataSetAdminOperationCompleted
            End If
            Me.InvokeAsync("admin_GetDataSetAdmin", New Object(-1) {}, Me.admin_GetDataSetAdminOperationCompleted, userState)
        End Sub
        
        Private Sub Onadmin_GetDataSetAdminOperationCompleted(ByVal arg As Object)
            If (Not (Me.admin_GetDataSetAdminCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent admin_GetDataSetAdminCompleted(Me, New admin_GetDataSetAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub auto_verhuurCompletedEventHandler(ByVal sender As Object, ByVal e As auto_verhuurCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class auto_verhuurCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub auto_addCompletedEventHandler(ByVal sender As Object, ByVal e As auto_addCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class auto_addCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub auto_updateCompletedEventHandler(ByVal sender As Object, ByVal e As auto_updateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class auto_updateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub auto_removeCompletedEventHandler(ByVal sender As Object, ByVal e As auto_removeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class auto_removeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub auto_getDataSetAutoCompletedEventHandler(ByVal sender As Object, ByVal e As auto_getDataSetAutoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class auto_getDataSetAutoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub klant_LoginCompletedEventHandler(ByVal sender As Object, ByVal e As klant_LoginCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class klant_LoginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub klant_insertCompletedEventHandler(ByVal sender As Object, ByVal e As klant_insertCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class klant_insertCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub klant_updateCompletedEventHandler(ByVal sender As Object, ByVal e As klant_updateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class klant_updateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub klant_removeCompletedEventHandler(ByVal sender As Object, ByVal e As klant_removeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class klant_removeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub klant_getDataSetKlantCompletedEventHandler(ByVal sender As Object, ByVal e As klant_getDataSetKlantCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class klant_getDataSetKlantCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub verhuur_addCompletedEventHandler(ByVal sender As Object, ByVal e As verhuur_addCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class verhuur_addCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub verhuur_updateCompletedEventHandler(ByVal sender As Object, ByVal e As verhuur_updateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class verhuur_updateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub verhuur_removeCompletedEventHandler(ByVal sender As Object, ByVal e As verhuur_removeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class verhuur_removeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub verhuur_getDataSetVerhuurCompletedEventHandler(ByVal sender As Object, ByVal e As verhuur_getDataSetVerhuurCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class verhuur_getDataSetVerhuurCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub connectionTestCompletedEventHandler(ByVal sender As Object, ByVal e As connectionTestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class connectionTestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub admin_LoginCompletedEventHandler(ByVal sender As Object, ByVal e As admin_LoginCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class admin_LoginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub admin_GetDataSetAdminCompletedEventHandler(ByVal sender As Object, ByVal e As admin_GetDataSetAdminCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class admin_GetDataSetAdminCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
