//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.261.
// 
#pragma warning disable 1591

namespace Front_end_C.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback auto_verhuurOperationCompleted;
        
        private System.Threading.SendOrPostCallback auto_addOperationCompleted;
        
        private System.Threading.SendOrPostCallback auto_updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback auto_removeOperationCompleted;
        
        private System.Threading.SendOrPostCallback auto_getDataSetAutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback klant_LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback klant_insertOperationCompleted;
        
        private System.Threading.SendOrPostCallback klant_updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback klant_removeOperationCompleted;
        
        private System.Threading.SendOrPostCallback klant_getDataSetKlantOperationCompleted;
        
        private System.Threading.SendOrPostCallback verhuur_addOperationCompleted;
        
        private System.Threading.SendOrPostCallback verhuur_updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback verhuur_removeOperationCompleted;
        
        private System.Threading.SendOrPostCallback verhuur_getDataSetVerhuurOperationCompleted;
        
        private System.Threading.SendOrPostCallback connectionTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback admin_LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback admin_GetDataSetAdminOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::Front_end_C.Properties.Settings.Default.Front_end_C_WebService_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event auto_verhuurCompletedEventHandler auto_verhuurCompleted;
        
        /// <remarks/>
        public event auto_addCompletedEventHandler auto_addCompleted;
        
        /// <remarks/>
        public event auto_updateCompletedEventHandler auto_updateCompleted;
        
        /// <remarks/>
        public event auto_removeCompletedEventHandler auto_removeCompleted;
        
        /// <remarks/>
        public event auto_getDataSetAutoCompletedEventHandler auto_getDataSetAutoCompleted;
        
        /// <remarks/>
        public event klant_LoginCompletedEventHandler klant_LoginCompleted;
        
        /// <remarks/>
        public event klant_insertCompletedEventHandler klant_insertCompleted;
        
        /// <remarks/>
        public event klant_updateCompletedEventHandler klant_updateCompleted;
        
        /// <remarks/>
        public event klant_removeCompletedEventHandler klant_removeCompleted;
        
        /// <remarks/>
        public event klant_getDataSetKlantCompletedEventHandler klant_getDataSetKlantCompleted;
        
        /// <remarks/>
        public event verhuur_addCompletedEventHandler verhuur_addCompleted;
        
        /// <remarks/>
        public event verhuur_updateCompletedEventHandler verhuur_updateCompleted;
        
        /// <remarks/>
        public event verhuur_removeCompletedEventHandler verhuur_removeCompleted;
        
        /// <remarks/>
        public event verhuur_getDataSetVerhuurCompletedEventHandler verhuur_getDataSetVerhuurCompleted;
        
        /// <remarks/>
        public event connectionTestCompletedEventHandler connectionTestCompleted;
        
        /// <remarks/>
        public event admin_LoginCompletedEventHandler admin_LoginCompleted;
        
        /// <remarks/>
        public event admin_GetDataSetAdminCompletedEventHandler admin_GetDataSetAdminCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/auto_verhuur", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string auto_verhuur(object[] gegevensArray) {
            object[] results = this.Invoke("auto_verhuur", new object[] {
                        gegevensArray});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void auto_verhuurAsync(object[] gegevensArray) {
            this.auto_verhuurAsync(gegevensArray, null);
        }
        
        /// <remarks/>
        public void auto_verhuurAsync(object[] gegevensArray, object userState) {
            if ((this.auto_verhuurOperationCompleted == null)) {
                this.auto_verhuurOperationCompleted = new System.Threading.SendOrPostCallback(this.Onauto_verhuurOperationCompleted);
            }
            this.InvokeAsync("auto_verhuur", new object[] {
                        gegevensArray}, this.auto_verhuurOperationCompleted, userState);
        }
        
        private void Onauto_verhuurOperationCompleted(object arg) {
            if ((this.auto_verhuurCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.auto_verhuurCompleted(this, new auto_verhuurCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/auto_add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string auto_add(object[] gegevensArray) {
            object[] results = this.Invoke("auto_add", new object[] {
                        gegevensArray});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void auto_addAsync(object[] gegevensArray) {
            this.auto_addAsync(gegevensArray, null);
        }
        
        /// <remarks/>
        public void auto_addAsync(object[] gegevensArray, object userState) {
            if ((this.auto_addOperationCompleted == null)) {
                this.auto_addOperationCompleted = new System.Threading.SendOrPostCallback(this.Onauto_addOperationCompleted);
            }
            this.InvokeAsync("auto_add", new object[] {
                        gegevensArray}, this.auto_addOperationCompleted, userState);
        }
        
        private void Onauto_addOperationCompleted(object arg) {
            if ((this.auto_addCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.auto_addCompleted(this, new auto_addCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/auto_update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string auto_update(object[] gegevensArray) {
            object[] results = this.Invoke("auto_update", new object[] {
                        gegevensArray});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void auto_updateAsync(object[] gegevensArray) {
            this.auto_updateAsync(gegevensArray, null);
        }
        
        /// <remarks/>
        public void auto_updateAsync(object[] gegevensArray, object userState) {
            if ((this.auto_updateOperationCompleted == null)) {
                this.auto_updateOperationCompleted = new System.Threading.SendOrPostCallback(this.Onauto_updateOperationCompleted);
            }
            this.InvokeAsync("auto_update", new object[] {
                        gegevensArray}, this.auto_updateOperationCompleted, userState);
        }
        
        private void Onauto_updateOperationCompleted(object arg) {
            if ((this.auto_updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.auto_updateCompleted(this, new auto_updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/auto_remove", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string auto_remove(int autoID) {
            object[] results = this.Invoke("auto_remove", new object[] {
                        autoID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void auto_removeAsync(int autoID) {
            this.auto_removeAsync(autoID, null);
        }
        
        /// <remarks/>
        public void auto_removeAsync(int autoID, object userState) {
            if ((this.auto_removeOperationCompleted == null)) {
                this.auto_removeOperationCompleted = new System.Threading.SendOrPostCallback(this.Onauto_removeOperationCompleted);
            }
            this.InvokeAsync("auto_remove", new object[] {
                        autoID}, this.auto_removeOperationCompleted, userState);
        }
        
        private void Onauto_removeOperationCompleted(object arg) {
            if ((this.auto_removeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.auto_removeCompleted(this, new auto_removeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/auto_getDataSetAuto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet auto_getDataSetAuto() {
            object[] results = this.Invoke("auto_getDataSetAuto", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void auto_getDataSetAutoAsync() {
            this.auto_getDataSetAutoAsync(null);
        }
        
        /// <remarks/>
        public void auto_getDataSetAutoAsync(object userState) {
            if ((this.auto_getDataSetAutoOperationCompleted == null)) {
                this.auto_getDataSetAutoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onauto_getDataSetAutoOperationCompleted);
            }
            this.InvokeAsync("auto_getDataSetAuto", new object[0], this.auto_getDataSetAutoOperationCompleted, userState);
        }
        
        private void Onauto_getDataSetAutoOperationCompleted(object arg) {
            if ((this.auto_getDataSetAutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.auto_getDataSetAutoCompleted(this, new auto_getDataSetAutoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/klant_Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet klant_Login(string Emailadres, string Wachtwoord) {
            object[] results = this.Invoke("klant_Login", new object[] {
                        Emailadres,
                        Wachtwoord});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void klant_LoginAsync(string Emailadres, string Wachtwoord) {
            this.klant_LoginAsync(Emailadres, Wachtwoord, null);
        }
        
        /// <remarks/>
        public void klant_LoginAsync(string Emailadres, string Wachtwoord, object userState) {
            if ((this.klant_LoginOperationCompleted == null)) {
                this.klant_LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.Onklant_LoginOperationCompleted);
            }
            this.InvokeAsync("klant_Login", new object[] {
                        Emailadres,
                        Wachtwoord}, this.klant_LoginOperationCompleted, userState);
        }
        
        private void Onklant_LoginOperationCompleted(object arg) {
            if ((this.klant_LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.klant_LoginCompleted(this, new klant_LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/klant_insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string klant_insert(object[] gegevensArray) {
            object[] results = this.Invoke("klant_insert", new object[] {
                        gegevensArray});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void klant_insertAsync(object[] gegevensArray) {
            this.klant_insertAsync(gegevensArray, null);
        }
        
        /// <remarks/>
        public void klant_insertAsync(object[] gegevensArray, object userState) {
            if ((this.klant_insertOperationCompleted == null)) {
                this.klant_insertOperationCompleted = new System.Threading.SendOrPostCallback(this.Onklant_insertOperationCompleted);
            }
            this.InvokeAsync("klant_insert", new object[] {
                        gegevensArray}, this.klant_insertOperationCompleted, userState);
        }
        
        private void Onklant_insertOperationCompleted(object arg) {
            if ((this.klant_insertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.klant_insertCompleted(this, new klant_insertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/klant_update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string klant_update(object[] gegevensArray) {
            object[] results = this.Invoke("klant_update", new object[] {
                        gegevensArray});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void klant_updateAsync(object[] gegevensArray) {
            this.klant_updateAsync(gegevensArray, null);
        }
        
        /// <remarks/>
        public void klant_updateAsync(object[] gegevensArray, object userState) {
            if ((this.klant_updateOperationCompleted == null)) {
                this.klant_updateOperationCompleted = new System.Threading.SendOrPostCallback(this.Onklant_updateOperationCompleted);
            }
            this.InvokeAsync("klant_update", new object[] {
                        gegevensArray}, this.klant_updateOperationCompleted, userState);
        }
        
        private void Onklant_updateOperationCompleted(object arg) {
            if ((this.klant_updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.klant_updateCompleted(this, new klant_updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/klant_remove", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string klant_remove(int klantID) {
            object[] results = this.Invoke("klant_remove", new object[] {
                        klantID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void klant_removeAsync(int klantID) {
            this.klant_removeAsync(klantID, null);
        }
        
        /// <remarks/>
        public void klant_removeAsync(int klantID, object userState) {
            if ((this.klant_removeOperationCompleted == null)) {
                this.klant_removeOperationCompleted = new System.Threading.SendOrPostCallback(this.Onklant_removeOperationCompleted);
            }
            this.InvokeAsync("klant_remove", new object[] {
                        klantID}, this.klant_removeOperationCompleted, userState);
        }
        
        private void Onklant_removeOperationCompleted(object arg) {
            if ((this.klant_removeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.klant_removeCompleted(this, new klant_removeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/klant_getDataSetKlant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet klant_getDataSetKlant() {
            object[] results = this.Invoke("klant_getDataSetKlant", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void klant_getDataSetKlantAsync() {
            this.klant_getDataSetKlantAsync(null);
        }
        
        /// <remarks/>
        public void klant_getDataSetKlantAsync(object userState) {
            if ((this.klant_getDataSetKlantOperationCompleted == null)) {
                this.klant_getDataSetKlantOperationCompleted = new System.Threading.SendOrPostCallback(this.Onklant_getDataSetKlantOperationCompleted);
            }
            this.InvokeAsync("klant_getDataSetKlant", new object[0], this.klant_getDataSetKlantOperationCompleted, userState);
        }
        
        private void Onklant_getDataSetKlantOperationCompleted(object arg) {
            if ((this.klant_getDataSetKlantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.klant_getDataSetKlantCompleted(this, new klant_getDataSetKlantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verhuur_add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool verhuur_add(object[] gegevensArray) {
            object[] results = this.Invoke("verhuur_add", new object[] {
                        gegevensArray});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void verhuur_addAsync(object[] gegevensArray) {
            this.verhuur_addAsync(gegevensArray, null);
        }
        
        /// <remarks/>
        public void verhuur_addAsync(object[] gegevensArray, object userState) {
            if ((this.verhuur_addOperationCompleted == null)) {
                this.verhuur_addOperationCompleted = new System.Threading.SendOrPostCallback(this.Onverhuur_addOperationCompleted);
            }
            this.InvokeAsync("verhuur_add", new object[] {
                        gegevensArray}, this.verhuur_addOperationCompleted, userState);
        }
        
        private void Onverhuur_addOperationCompleted(object arg) {
            if ((this.verhuur_addCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verhuur_addCompleted(this, new verhuur_addCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verhuur_update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string verhuur_update(object[] gegevensArray) {
            object[] results = this.Invoke("verhuur_update", new object[] {
                        gegevensArray});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void verhuur_updateAsync(object[] gegevensArray) {
            this.verhuur_updateAsync(gegevensArray, null);
        }
        
        /// <remarks/>
        public void verhuur_updateAsync(object[] gegevensArray, object userState) {
            if ((this.verhuur_updateOperationCompleted == null)) {
                this.verhuur_updateOperationCompleted = new System.Threading.SendOrPostCallback(this.Onverhuur_updateOperationCompleted);
            }
            this.InvokeAsync("verhuur_update", new object[] {
                        gegevensArray}, this.verhuur_updateOperationCompleted, userState);
        }
        
        private void Onverhuur_updateOperationCompleted(object arg) {
            if ((this.verhuur_updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verhuur_updateCompleted(this, new verhuur_updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verhuur_remove", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string verhuur_remove(int verhuurID) {
            object[] results = this.Invoke("verhuur_remove", new object[] {
                        verhuurID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void verhuur_removeAsync(int verhuurID) {
            this.verhuur_removeAsync(verhuurID, null);
        }
        
        /// <remarks/>
        public void verhuur_removeAsync(int verhuurID, object userState) {
            if ((this.verhuur_removeOperationCompleted == null)) {
                this.verhuur_removeOperationCompleted = new System.Threading.SendOrPostCallback(this.Onverhuur_removeOperationCompleted);
            }
            this.InvokeAsync("verhuur_remove", new object[] {
                        verhuurID}, this.verhuur_removeOperationCompleted, userState);
        }
        
        private void Onverhuur_removeOperationCompleted(object arg) {
            if ((this.verhuur_removeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verhuur_removeCompleted(this, new verhuur_removeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verhuur_getDataSetVerhuur", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet verhuur_getDataSetVerhuur() {
            object[] results = this.Invoke("verhuur_getDataSetVerhuur", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void verhuur_getDataSetVerhuurAsync() {
            this.verhuur_getDataSetVerhuurAsync(null);
        }
        
        /// <remarks/>
        public void verhuur_getDataSetVerhuurAsync(object userState) {
            if ((this.verhuur_getDataSetVerhuurOperationCompleted == null)) {
                this.verhuur_getDataSetVerhuurOperationCompleted = new System.Threading.SendOrPostCallback(this.Onverhuur_getDataSetVerhuurOperationCompleted);
            }
            this.InvokeAsync("verhuur_getDataSetVerhuur", new object[0], this.verhuur_getDataSetVerhuurOperationCompleted, userState);
        }
        
        private void Onverhuur_getDataSetVerhuurOperationCompleted(object arg) {
            if ((this.verhuur_getDataSetVerhuurCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verhuur_getDataSetVerhuurCompleted(this, new verhuur_getDataSetVerhuurCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/connectionTest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool connectionTest() {
            object[] results = this.Invoke("connectionTest", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void connectionTestAsync() {
            this.connectionTestAsync(null);
        }
        
        /// <remarks/>
        public void connectionTestAsync(object userState) {
            if ((this.connectionTestOperationCompleted == null)) {
                this.connectionTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconnectionTestOperationCompleted);
            }
            this.InvokeAsync("connectionTest", new object[0], this.connectionTestOperationCompleted, userState);
        }
        
        private void OnconnectionTestOperationCompleted(object arg) {
            if ((this.connectionTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.connectionTestCompleted(this, new connectionTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/admin_Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet admin_Login(string Emailadres, string Wachtwoord) {
            object[] results = this.Invoke("admin_Login", new object[] {
                        Emailadres,
                        Wachtwoord});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void admin_LoginAsync(string Emailadres, string Wachtwoord) {
            this.admin_LoginAsync(Emailadres, Wachtwoord, null);
        }
        
        /// <remarks/>
        public void admin_LoginAsync(string Emailadres, string Wachtwoord, object userState) {
            if ((this.admin_LoginOperationCompleted == null)) {
                this.admin_LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadmin_LoginOperationCompleted);
            }
            this.InvokeAsync("admin_Login", new object[] {
                        Emailadres,
                        Wachtwoord}, this.admin_LoginOperationCompleted, userState);
        }
        
        private void Onadmin_LoginOperationCompleted(object arg) {
            if ((this.admin_LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.admin_LoginCompleted(this, new admin_LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/admin_GetDataSetAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet admin_GetDataSetAdmin() {
            object[] results = this.Invoke("admin_GetDataSetAdmin", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void admin_GetDataSetAdminAsync() {
            this.admin_GetDataSetAdminAsync(null);
        }
        
        /// <remarks/>
        public void admin_GetDataSetAdminAsync(object userState) {
            if ((this.admin_GetDataSetAdminOperationCompleted == null)) {
                this.admin_GetDataSetAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadmin_GetDataSetAdminOperationCompleted);
            }
            this.InvokeAsync("admin_GetDataSetAdmin", new object[0], this.admin_GetDataSetAdminOperationCompleted, userState);
        }
        
        private void Onadmin_GetDataSetAdminOperationCompleted(object arg) {
            if ((this.admin_GetDataSetAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.admin_GetDataSetAdminCompleted(this, new admin_GetDataSetAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void auto_verhuurCompletedEventHandler(object sender, auto_verhuurCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class auto_verhuurCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal auto_verhuurCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void auto_addCompletedEventHandler(object sender, auto_addCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class auto_addCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal auto_addCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void auto_updateCompletedEventHandler(object sender, auto_updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class auto_updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal auto_updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void auto_removeCompletedEventHandler(object sender, auto_removeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class auto_removeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal auto_removeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void auto_getDataSetAutoCompletedEventHandler(object sender, auto_getDataSetAutoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class auto_getDataSetAutoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal auto_getDataSetAutoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void klant_LoginCompletedEventHandler(object sender, klant_LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class klant_LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal klant_LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void klant_insertCompletedEventHandler(object sender, klant_insertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class klant_insertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal klant_insertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void klant_updateCompletedEventHandler(object sender, klant_updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class klant_updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal klant_updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void klant_removeCompletedEventHandler(object sender, klant_removeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class klant_removeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal klant_removeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void klant_getDataSetKlantCompletedEventHandler(object sender, klant_getDataSetKlantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class klant_getDataSetKlantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal klant_getDataSetKlantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void verhuur_addCompletedEventHandler(object sender, verhuur_addCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verhuur_addCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verhuur_addCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void verhuur_updateCompletedEventHandler(object sender, verhuur_updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verhuur_updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verhuur_updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void verhuur_removeCompletedEventHandler(object sender, verhuur_removeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verhuur_removeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verhuur_removeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void verhuur_getDataSetVerhuurCompletedEventHandler(object sender, verhuur_getDataSetVerhuurCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verhuur_getDataSetVerhuurCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verhuur_getDataSetVerhuurCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void connectionTestCompletedEventHandler(object sender, connectionTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class connectionTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal connectionTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void admin_LoginCompletedEventHandler(object sender, admin_LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class admin_LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal admin_LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void admin_GetDataSetAdminCompletedEventHandler(object sender, admin_GetDataSetAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class admin_GetDataSetAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal admin_GetDataSetAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591